In [15]:
import numpy as mi

In [16]:
a=mi.array([1,2,3,4])

In [17]:
print(a)

[1 2 3 4]


In [19]:
c=mi.array([(1,2,3),
            (5,6,7)])

In [20]:
print(c)

[[1 2 3]
 [5 6 7]]


In [21]:
trans=mi.transpose(c)

In [22]:
print(trans)

[[1 5]
 [2 6]
 [3 7]]


In [23]:
trans.ravel()

array([1, 5, 2, 6, 3, 7])

In [24]:
c.reshape(2,3)

array([[1, 2, 3],
       [5, 6, 7]])

In [25]:
d=mi.zeros((3,2))

In [26]:
print(d)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [27]:
n=mi.ones((3,3))

In [28]:
print(n)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [31]:
mi.append(a,c)

array([1, 2, 3, 4, 1, 2, 3, 5, 6, 7])

In [38]:
mi.insert(a,4,4)

array([1, 2, 3, 4, 4])

In [40]:
mi.delete(a,[3])

array([1, 2, 3])

In [44]:
mi.random.random((3,3))

array([[0.94294792, 0.77775026, 0.94693474],
       [0.82434248, 0.00998077, 0.62038446],
       [0.2045479 , 0.19512243, 0.75561355]])